import 'brand.dart';
import 'category.dart';
import 'customer.dart';
import 'loyalty_card.dart';
import 'product.dart';
import 'supplier.dart';

final List<Supplier> seedSuppliers = [
  const Supplier(
    id: 1,
    name: 'Royal Canin Distribution',
    country: 'Франция',
    contactPerson: 'Жан-Люк Дюпон',
    phone: '+7 (495) 123-45-67',
    email: 'contact@royalcanin.fr',
    rating: 4.9,
  ),
  const Supplier(
    id: 2,
    name: 'Purina Russia',
    country: 'США',
    contactPerson: 'Марк Джонсон',
    phone: '+7 (495) 234-56-78',
    email: 'info@purina.com',
    rating: 4.8,
  ),
  const Supplier(
    id: 3,
    name: 'Tetra Russia',
    country: 'Германия',
    contactPerson: 'Ганс Шмидт',
    phone: '+7 (495) 345-67-89',
    email: 'support@tetra.net',
    rating: 4.7,
  ),
  const Supplier(
    id: 4,
    name: 'Ferplast Import',
    country: 'Италия',
    contactPerson: 'Марко Росси',
    phone: '+7 (495) 456-78-90',
    email: 'sales@ferplast.it',
    rating: 4.6,
  ),
  const Supplier(
    id: 5,
    name: 'Beaphar Nord',
    country: 'Нидерланды',
    contactPerson: 'Виллем ван Дейк',
    phone: '+7 (495) 567-89-01',
    email: 'nl@beaphar.com',
    rating: 4.7,
  ),
  const Supplier(
    id: 6,
    name: 'Triol Wholesale',
    country: 'Россия',
    contactPerson: 'Алексей Иванов',
    phone: '+7 (495) 678-90-12',
    email: 'orders@triol.ru',
    rating: 4.4,
  ),
  const Supplier(
    id: 7,
    name: 'Hill\'s Pet Nutrition',
    country: 'США',
    contactPerson: 'Сара Коннор',
    phone: '+7 (495) 789-01-23',
    email: 'contact@hills.com',
    rating: 4.8,
  ),
  const Supplier(
    id: 8,
    name: 'Mars Petcare RU',
    country: 'Россия',
    contactPerson: 'Елена Смирнова',
    phone: '+7 (495) 890-12-34',
    email: 'corp@mars.ru',
    rating: 4.2,
  ),
  const Supplier(
    id: 9,
    name: 'Savic Belgium',
    country: 'Бельгия',
    contactPerson: 'Люк де Смет',
    phone: '+7 (495) 901-23-45',
    email: 'info@savic.be',
    rating: 4.5,
  ),
  const Supplier(
    id: 10,
    name: 'Trixie Export',
    country: 'Германия',
    contactPerson: 'Карл Вебер',
    phone: '+7 (495) 012-34-56',
    email: 'export@trixie.de',
    rating: 4.6,
  ),
];

final List<ProductCategory> seedCategories = [
  const ProductCategory(
    id: 1,
    name: 'Корма и лакомства',
    description: 'Сухие и влажные корма, лакомства',
    iconName: 'pets',
  ),
  const ProductCategory(
    id: 2,
    name: 'Игрушки и развлечения',
    description: 'Игрушки для кошек, собак и грызунов',
    iconName: 'sports_esports',
  ),
  const ProductCategory(
    id: 3,
    name: 'Аквариумистика',
    description: 'Аквариумы, фильтры, корм для рыб',
    iconName: 'set_meal',
  ),
  const ProductCategory(
    id: 4,
    name: 'Ветаптека и уход',
    description: 'Витамины, шампуни, средства от паразитов',
    iconName: 'medical_services',
  ),
  const ProductCategory(
    id: 5,
    name: 'Амуниция и клетки',
    description: 'Поводки, клетки, переноски',
    iconName: 'home',
  ),
];

final List<Brand> seedBrands = [
  const Brand(
    id: 1,
    name: 'Royal Canin',
    country: 'Франция',
    description: 'Премиальные корма для собак и кошек',
    supplierIds: [1],
  ),
  const Brand(
    id: 2,
    name: 'Purina Pro Plan',
    country: 'США',
    description: 'Научно обоснованное питание',
    supplierIds: [2],
  ),
  const Brand(
    id: 3,
    name: 'Tetra',
    country: 'Германия',
    description: 'Оборудование и корма для аквариума',
    supplierIds: [3],
  ),
  const Brand(
    id: 4,
    name: 'Ferplast',
    country: 'Италия',
    description: 'Клетки и аксессуары',
    supplierIds: [4],
  ),
  const Brand(
    id: 5,
    name: 'Beaphar',
    country: 'Нидерланды',
    description: 'Ветеринарная аптека',
    supplierIds: [5],
  ),
  const Brand(
    id: 6,
    name: 'Triol',
    country: 'Россия',
    description: 'Игрушки и амуниция',
    supplierIds: [6],
  ),
  const Brand(
    id: 7,
    name: 'Hill\'s',
    country: 'США',
    description: 'Лечебные корма',
    supplierIds: [7],
  ),
  const Brand(
    id: 8,
    name: 'Whiskas',
    country: 'Россия',
    description: 'Корма для кошек',
    supplierIds: [8],
  ),
  const Brand(
    id: 9,
    name: 'Savic',
    country: 'Бельгия',
    description: 'Клетки для грызунов',
    supplierIds: [9],
  ),
  const Brand(
    id: 10,
    name: 'Trixie',
    country: 'Германия',
    description: 'Игрушки и аксессуары',
    supplierIds: [10, 6],
  ),
  const Brand(
    id: 11,
    name: 'Pedigree',
    country: 'Россия',
    description: 'Корма и лакомства для собак',
    supplierIds: [8],
  ),
];

final List<Product> seedProducts = [
  const Product(
    id: 1,
    name: 'Сухой корм Royal Canin Maxi Adult 15кг',
    sku: 'PET-1001',
    supplierId: 1,
    categoryIds: [1],
    brandIds: [1],
    price: 6490,
    stock: 45,
    rating: 4.9,
  ),
  const Product(
    id: 2,
    name: 'Влажный корм Purina Pro Plan Sterilised 85г',
    sku: 'PET-1002',
    supplierId: 2,
    categoryIds: [1],
    brandIds: [2],
    price: 85,
    stock: 350,
    rating: 4.8,
  ),
  const Product(
    id: 3,
    name: 'Аквариумный комплект Tetra AquaArt 60L LED',
    sku: 'PET-1003',
    supplierId: 3,
    categoryIds: [3],
    brandIds: [3],
    price: 14500,
    stock: 8,
    rating: 4.9,
  ),
  const Product(
    id: 4,
    name: 'Клетка для птиц Ferplast Rekord 3',
    sku: 'PET-1004',
    supplierId: 4,
    categoryIds: [5],
    brandIds: [4],
    price: 5200,
    stock: 12,
    rating: 4.6,
  ),
  const Product(
    id: 5,
    name: 'Капли от блох Beaphar Spot-On 3 пипетки',
    sku: 'PET-1005',
    supplierId: 5,
    categoryIds: [4],
    brandIds: [5],
    price: 890,
    stock: 75,
    rating: 4.7,
  ),
  const Product(
    id: 6,
    name: 'Игрушка Triol Мышка на пружине',
    sku: 'PET-1006',
    supplierId: 6,
    categoryIds: [2],
    brandIds: [6],
    price: 240,
    stock: 120,
    rating: 4.3,
  ),
  const Product(
    id: 7,
    name: 'Лечебный корм Hill\'s i/d 2кг',
    sku: 'PET-1007',
    supplierId: 7,
    categoryIds: [1, 4],
    brandIds: [7],
    price: 2950,
    stock: 22,
    rating: 4.9,
  ),
  const Product(
    id: 8,
    name: 'Паучи Whiskas Желе с говядиной 75г',
    sku: 'PET-1008',
    supplierId: 8,
    categoryIds: [1],
    brandIds: [8],
    price: 32,
    stock: 500,
    rating: 4.1,
  ),
  const Product(
    id: 9,
    name: 'Клетка для грызунов Savic Spilos 50',
    sku: 'PET-1009',
    supplierId: 9,
    categoryIds: [5],
    brandIds: [9],
    price: 4300,
    stock: 15,
    rating: 4.5,
  ),
  const Product(
    id: 10,
    name: 'Когтеточка Trixie столбик 50см',
    sku: 'PET-1010',
    supplierId: 10,
    categoryIds: [2, 5],
    brandIds: [10],
    price: 1850,
    stock: 30,
    rating: 4.6,
  ),
  const Product(
    id: 11,
    name: 'Сухой корм Royal Canin Kitten 4кг',
    sku: 'PET-1011',
    supplierId: 1,
    categoryIds: [1],
    brandIds: [1],
    price: 2890,
    stock: 60,
    rating: 4.9,
  ),
  const Product(
    id: 12,
    name: 'Корм для рыбок TetraMin Flakes 250мл',
    sku: 'PET-1012',
    supplierId: 3,
    categoryIds: [1, 3],
    brandIds: [3],
    price: 620,
    stock: 90,
    rating: 4.8,
  ),
  const Product(
    id: 13,
    name: 'Шампунь Beaphar противопаразитарный 250мл',
    sku: 'PET-1013',
    supplierId: 5,
    categoryIds: [4],
    brandIds: [5],
    price: 540,
    stock: 40,
    rating: 4.5,
  ),
  const Product(
    id: 14,
    name: 'Поводок-рулетка Triol Neon 5м',
    sku: 'PET-1014',
    supplierId: 6,
    categoryIds: [5],
    brandIds: [6],
    price: 1290,
    stock: 35,
    rating: 4.4,
  ),
  const Product(
    id: 15,
    name: 'Мячик Trixie со свистком D-6см',
    sku: 'PET-1015',
    supplierId: 10,
    categoryIds: [2],
    brandIds: [10],
    price: 290,
    stock: 180,
    rating: 4.7,
  ),
  const Product(
    id: 16,
    name: 'Сухой корм Purina Duo Delice 10кг',
    sku: 'PET-1016',
    supplierId: 2,
    categoryIds: [1],
    brandIds: [2],
    price: 5900,
    stock: 28,
    rating: 4.8,
  ),
  const Product(
    id: 17,
    name: 'Фильтр Tetra EasyCrystal 300',
    sku: 'PET-1017',
    supplierId: 3,
    categoryIds: [3],
    brandIds: [3],
    price: 2350,
    stock: 19,
    rating: 4.7,
  ),
  const Product(
    id: 18,
    name: 'Переноска Ferplast Atlas 10 EL',
    sku: 'PET-1018',
    supplierId: 4,
    categoryIds: [5],
    brandIds: [4],
    price: 2790,
    stock: 25,
    rating: 4.8,
  ),
  const Product(
    id: 19,
    name: 'Мультивитамины Beaphar Top 10 180 таб',
    sku: 'PET-1019',
    supplierId: 5,
    categoryIds: [4],
    brandIds: [5],
    price: 990,
    stock: 50,
    rating: 4.8,
  ),
  const Product(
    id: 20,
    name: 'Туннель Trixie для кошек 50см',
    sku: 'PET-1020',
    supplierId: 10,
    categoryIds: [2],
    brandIds: [10],
    price: 1150,
    stock: 20,
    rating: 4.5,
  ),
  const Product(
    id: 21,
    name: 'Корм для попугаев Triol 500г',
    sku: 'PET-1021',
    supplierId: 6,
    categoryIds: [1],
    brandIds: [6],
    price: 190,
    stock: 110,
    rating: 4.3,
  ),
  const Product(
    id: 22,
    name: 'Лакомство Pedigree DentaStix 7шт',
    sku: 'PET-1022',
    supplierId: 8,
    categoryIds: [1],
    brandIds: [11],
    price: 240,
    stock: 160,
    rating: 4.6,
  ),
  const Product(
    id: 23,
    name: 'Автопоилка Savic Aqua Boy 500мл',
    sku: 'PET-1023',
    supplierId: 9,
    categoryIds: [5],
    brandIds: [9],
    price: 680,
    stock: 40,
    rating: 4.4,
  ),
  const Product(
    id: 24,
    name: 'Терморегулятор Tetra HT 50W',
    sku: 'PET-1024',
    supplierId: 3,
    categoryIds: [3],
    brandIds: [3],
    price: 1980,
    stock: 14,
    rating: 4.8,
  ),
  const Product(
    id: 25,
    name: 'Спрей Beaphar отпугивающий 125мл',
    sku: 'PET-1025',
    supplierId: 5,
    categoryIds: [4],
    brandIds: [5],
    price: 720,
    stock: 33,
    rating: 4.2,
  ),
];

final List<Customer> seedCustomers = [
  Customer(
    id: 1,
    fullName: 'Анна Петрова',
    email: 'anna.petrova@mail.ru',
    phone: '+7 (916) 111-22-33',
    card: LoyaltyCard(
      number: 'LC-10001',
      issuedAt: DateTime(2024, 3, 12),
      points: 1250,
      level: 'Золото',
    ),
  ),
  Customer(
    id: 2,
    fullName: 'Игорь Сидоров',
    email: 'igor.sidorov@gmail.com',
    phone: '+7 (903) 222-33-44',
    card: LoyaltyCard(
      number: 'LC-10002',
      issuedAt: DateTime(2025, 1, 8),
      points: 320,
      level: 'Стандарт',
    ),
  ),
  Customer(
    id: 3,
    fullName: 'Мария Козлова',
    email: 'm.kozlova@yandex.ru',
    phone: '+7 (926) 333-44-55',
    card: LoyaltyCard(
      number: 'LC-10003',
      issuedAt: DateTime(2023, 11, 20),
      points: 4800,
      level: 'Платина',
    ),
  ),
  Customer(
    id: 4,
    fullName: 'Дмитрий Орлов',
    email: 'd.orlov@outlook.com',
    phone: '+7 (999) 444-55-66',
    card: LoyaltyCard(
      number: 'LC-10004',
      issuedAt: DateTime(2024, 7, 1),
      points: 890,
      level: 'Серебро',
    ),
  ),
  Customer(
    id: 5,
    fullName: 'Елена Васильева',
    email: 'elena.v@petmail.ru',
    phone: '+7 (915) 555-66-77',
    card: LoyaltyCard(
      number: 'LC-10005',
      issuedAt: DateTime(2025, 5, 15),
      points: 150,
      level: 'Стандарт',
    ),
  ),
];
